fix: add ApacheJMeter_components dependency for AbstractListener
The SLOReporter extends org.apache.jmeter.reporters.AbstractListener
which is provided by ApacheJMeter_components, not ApacheJMeter_core.

This fixes the compilation error:
  symbol: class AbstractListener
  location: package org.apache.jmeter.reporters

Also adds scope=provided to ensure the JAR doesn't include JMeter
classes (they are provided at runtime by JMeter).